import { randomUUID } from 'node:crypto';
import type { NextFunction, Request, Response } from 'express';

export const CORRELATION_ID_HEADER = 'X-Correlation-Id';
export const REQUEST_ID_HEADER = 'X-Request-Id';

/** Express request carrying the ids assigned by `correlationIdMiddleware`. */
export type RequestWithCorrelationId = Request & {
  /** Chosen by the server. Ties API → outbox → queue → consumer → audit together (NFR-OBS-01). */
  correlationId?: string;
  /** Sent by the caller, kept only so it can be echoed back. Never used for tracing or audit. */
  clientRequestId?: string;
};

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Gives every request a correlation id and echoes it in `X-Correlation-Id`.
 *
 * The correlation id is ALWAYS generated by the server. If a caller could choose it, anyone could
 * reuse another person's id and pollute the audit search for that request. A caller's own
 * identifier travels separately as `X-Request-Id`: it is echoed back so the client can match a
 * response to its request, and it is dropped unless it is a well-formed UUID, so it can never
 * inject arbitrary text (log forging) into our logs.
 */
export function correlationIdMiddleware(
  req: RequestWithCorrelationId,
  res: Response,
  next: NextFunction,
): void {
  const correlationId = randomUUID();
  req.correlationId = correlationId;
  res.setHeader(CORRELATION_ID_HEADER, correlationId);

  const incoming = req.header(REQUEST_ID_HEADER);
  if (incoming && UUID_PATTERN.test(incoming)) {
    req.clientRequestId = incoming.toLowerCase();
    res.setHeader(REQUEST_ID_HEADER, req.clientRequestId);
  }
  next();
}
