import type { Response } from 'express';
import {
  CORRELATION_ID_HEADER,
  correlationIdMiddleware,
  REQUEST_ID_HEADER,
  type RequestWithCorrelationId,
} from './correlation-id.middleware';

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const SOME_UUID = '3F2504E0-4F89-41D3-9A0C-0305E82C3301';

function run(headers: Record<string, string> = {}) {
  const req = {
    header: jest.fn((name: string) => headers[name]),
  } as unknown as RequestWithCorrelationId;
  const res = { setHeader: jest.fn() } as unknown as Response;
  const next = jest.fn();
  correlationIdMiddleware(req, res, next);
  return { req, res, next };
}

describe('correlationIdMiddleware', () => {
  describe('correlation id (ties API → outbox → consumer → audit together)', () => {
    it('is generated by the server and returned in the response header', () => {
      const { req, res, next } = run();
      expect(req.correlationId).toMatch(UUID);
      expect(res.setHeader).toHaveBeenCalledWith(CORRELATION_ID_HEADER, req.correlationId);
      expect(next).toHaveBeenCalledTimes(1);
    });

    it('can NOT be chosen by the caller, so nobody can reuse a victim id to pollute audit searches', () => {
      const { req } = run({ [CORRELATION_ID_HEADER]: SOME_UUID });
      expect(req.correlationId).toMatch(UUID);
      expect(req.correlationId).not.toBe(SOME_UUID.toLowerCase());
    });

    it('is different for every request', () => {
      expect(run().req.correlationId).not.toBe(run().req.correlationId);
    });
  });

  describe('caller request id (for the client to match a response to its own request)', () => {
    it('keeps a well-formed id separately from the correlation id and echoes it back', () => {
      const { req, res } = run({ [REQUEST_ID_HEADER]: SOME_UUID });
      expect(req.clientRequestId).toBe(SOME_UUID.toLowerCase());
      expect(req.correlationId).not.toBe(req.clientRequestId);
      expect(res.setHeader).toHaveBeenCalledWith(REQUEST_ID_HEADER, SOME_UUID.toLowerCase());
    });

    it('is absent when the caller sends none', () => {
      const { req, res } = run();
      expect(req.clientRequestId).toBeUndefined();
      expect(res.setHeader).not.toHaveBeenCalledWith(REQUEST_ID_HEADER, expect.anything());
    });

    it.each(['not-a-uuid', 'x'.repeat(500), `${SOME_UUID}\nforged: line`])(
      'drops a malformed id so it cannot forge log lines: %j',
      bad => {
        const { req, res } = run({ [REQUEST_ID_HEADER]: bad });
        expect(req.clientRequestId).toBeUndefined();
        expect(res.setHeader).not.toHaveBeenCalledWith(REQUEST_ID_HEADER, expect.anything());
      },
    );
  });
});
